version: '3'

services:
  valkey-1:
    container_name: valkey-1
    image: valkey/valkey
    command: valkey-server /etc/valkey.conf
    volumes:
      - ./valkey-1.conf:/etc/valkey.conf
    restart: always
    expose:
      - 7001
      - 17001
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "17001:17001"
      - "17002:17002"
      - "17003:17003"
      - "17004:17004"
      - "17005:17005"
      - "17006:17006"

  valkey-2:
    container_name: valkey-2
    image: valkey/valkey
    command: valkey-server /etc/valkey.conf
    volumes:
      - ./valkey-2.conf:/etc/valkey.conf
    restart: always
    network_mode: "service:valkey-1"
    expose:
      - 7002
      - 17002

  valkey-3:
    container_name: valkey-3
    image: valkey/valkey
    command: valkey-server /etc/valkey.conf
    volumes:
      - ./valkey-3.conf:/etc/valkey.conf
    restart: always
    network_mode: "service:valkey-1"
    expose:
      - 7003
      - 17003

  valkey-4:
    container_name: valkey-4
    image: valkey/valkey
    command: valkey-server /etc/valkey.conf
    volumes:
      - ./valkey-4.conf:/etc/valkey.conf
    restart: always
    network_mode: "service:valkey-1"
    expose:
      - 7004
      - 17004

  valkey-5:
    container_name: valkey-5
    image: valkey/valkey
    command: valkey-server /etc/valkey.conf
    volumes:
      - ./valkey-5.conf:/etc/valkey.conf
    restart: always
    network_mode: "service:valkey-1"
    expose:
      - 7005
      - 17005

  valkey-6:
    container_name: valkey-6
    image: valkey/valkey
    command: valkey-server /etc/valkey.conf
    volumes:
      - ./valkey-6.conf:/etc/valkey.conf
    restart: always
    network_mode: "service:valkey-1"
    expose:
      - 7006
      - 17006

  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    network_mode: "service:valkey-1"
    expose:
      - 5432
    ports:
      - "5432:5432"