version: "3"
services:
  server:
    image: "server:latest"
    ports:
      - "8080:8080"
    depends_on:
      - cache
    networks:
      - cache-network
  cache:
    image: "docker.io/library/valkey/valkey:8.0.2"
    expose:
      - "6379"
    networks:
      - cache-network
networks:
  cache-network: