// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	ID        int32
	Name      string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Node struct {
	ID        int32
	ClusterID int32
	NodeID    string
	Host      string
	Port      int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Password struct {
	ID   int32
	Salt string
	Hash string
}

type User struct {
	ID        int32
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
