// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Password    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Node struct {
	ID        int32
	ClusterID int32
	NodeID    string
	Host      string
	Port      int32
	Connected bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Password struct {
	ID   int32
	Salt string
	Hash string
}

type Session struct {
	ID        int32
	UserID    int32
	Token     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Expired   bool
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Email     string
	IsAdmin   bool
	Validated bool
	Deleted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
